### PR TITLE
Add new default headers X-Frame-Options, X-Content-Type-Options and X-XSS-Protection to protect request agains security attacks

### PR DESCRIPTION
**Pull request by wagnert**

### CODE REVIEW

**Comment by 2case** [comment]
Great... :( ... and how can i disable or change the x-frame-options??? Where is the documentation for this?

**Comment by wagnert** [comment]
@2case Have a look at http://appserver.io/get-started/documentation/1.1/webserver.html#headers, there is described, how you can override the value of the `X-Frame-Options` header :)

**Comment by 2case** [comment]
Cool, thanks. Didn't found it by my own search and the new default value break neos on asset assignment. It will also break the reworked ui - as far as i heard - since the new one will based on iframes.

**Comment by wagnert** [comment]
You're welcome :)

**Comment by 2case** [comment]
Works perfect in the `appserver.xml` configuration file (added in case someone else look for this)
```
<headers>
    <header type="response" name="X-Frame-Options" value="SAMEORIGIN" override="true"/>
</headers>
```

**Pull request merged**
