### PR TITLE
[ADD] Overwrite autoloader file

### PR DESCRIPTION
**Pull request by michaeldoehler**
Overwrite the autoloader file to allow class loading for developing custom web server modules.

### CODE REVIEW

**Comment by zelgerj** [comment]
@appserver-ci test this

**Comment by zelgerj** [comment]
@michaeldoehler Thanks for contributing this! 👍 
Could you please fix the code style issues:

```
phpcs:
     [exec] 
     [exec] FILE: ...var/build/workspace/github_appserver-io_webserver/src/server.php
     [exec] ----------------------------------------------------------------------
     [exec] FOUND 4 ERRORS AFFECTING 2 LINES
     [exec] ----------------------------------------------------------------------
     [exec]  32 | ERROR | [x] Expected 1 space after IF keyword; 0 found
     [exec]  32 | ERROR | [x] Expected 1 space after closing parenthesis; found
     [exec]     |       |     ""
     [exec]  34 | ERROR | [x] Expected 1 space after closing brace; 0 found
     [exec]  34 | ERROR | [x] Expected 1 space after ELSE keyword; 0 found
     [exec] ----------------------------------------------------------------------
     [exec] PHPCBF CAN FIX THE 4 MARKED SNIFF VIOLATIONS AUTOMATICALLY
     [exec] ----------------------------------------------------------------------
     [exec] 
     [exec] Time: 9.49 secs; Memory: 20.5Mb
     [exec] 
```

**Comment by michaeldoehler** [comment]
Fix is done, hopefully :)

**Comment by zelgerj** [comment]
Perfect! Thanks!

**Pull request merged**
